### ISSUE TITLE
Startup Crash on 1.19.2 version 1.4.10

### ISSUE THREAD

**Issue by Mqony** [Minecraft-LightLand/L2Complements#10]
The game will not startup and will leave this error message in the logs:

[pool-4-thread-1/FATAL]: Mixin apply failed l2complements.mixins.json:ItemEntityMixin -> net.minecraft.world.entity.item.ItemEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/entity/item/ItemEntity::l2complments_hurt_itemBurnt with priority 1000 cannot inject into net/minecraft/world/entity/item/ItemEntity::m_6469_(Lnet/minecraft/world/damagesource/DamageSource;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> l2complements.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> handler$fci000$l2complments_hurt_itemBurnt(Lnet/minecraft/world/damagesource/DamageSource;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/entity/item/ItemEntity::l2complments_hurt_itemBurnt with priority 1000 cannot inject into net/minecraft/world/entity/item/ItemEntity::m_6469_(Lnet/minecraft/world/damagesource/DamageSource;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> l2complements.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> handler$fci000$l2complments_hurt_itemBurnt(Lnet/minecraft/world/damagesource/DamageSource;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]

The crash does not happen on 1.4.9, but the problem is that I need to use version 1.4.10 since it's the only version on 1.19.2 compatible with L2 Hostility,

**Comment by lcy0x1** [comment]
same old problem. ItemPhysics is not compatible with L2Complements. Their dev fixed it in 1.20, but they don't support 1.19 anymore
