### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LoloElSupremo** [Minecraft-LightLand/L2Complements#5]
L2 addons once added to my modpack causes an error on startup. I have no crash report, just logs with not much...
https://pastebin.com/7qYnXvRR

**Comment by lcy0x1** [comment]
This is because there are other mods that use Mixin Extra, but selects a different mod name.

I will ask Forge team and author of MixinExtra how to resolve this issue. Nothing can be done on my side except giving you a special build.

**Comment by lcy0x1** [comment]
It seems to be a Forge issue about JarJar. It’s not something that can be resolved entirely on my side. 

However, if you are able to join my discord, I can work with you to give you a working build that fix your issue. But it may contain multiple attempts so I need your active cooperation.

**Comment by lcy0x1** [comment]
<img width="835" alt="Screen Shot 2023-05-12 at 13 48 41" src="https://github.com/Minecraft-LightLand/L2Complements/assets/31638432/3b006fef-eab1-4a11-b94a-b6ff519bcb59">
As per Orion, I can't fix it

**Comment by lcy0x1** [comment]
Anyway, if you are using 1.19.2, you should not use debugify.

**Comment by lcy0x1** [comment]
Author of MixinExtras also replied:
<img width="871" alt="Screen Shot 2023-05-12 at 14 26 56" src="https://github.com/Minecraft-LightLand/L2Complements/assets/31638432/7768c71b-c822-401b-a22a-83f32f3d0e51">
