### ISSUE TITLE
mixin? startup crash

### ISSUE THREAD

**Issue by kaairu** [Minecraft-LightLand/L2Complements#8]
l2complements ver: 2.4.21

log:
https://mclo.gs/n02s1rW

**Comment by lcy0x1** [comment]
You are using 2.4.22.
The bug should be fixed in 2.4.23. Try that

**Comment by kaairu** [comment]
works now. CF app didn't show 2.4.23 available for some reason

**Comment by lcy0x1** [comment]
Because it's just updated.
