### ISSUE TITLE
似乎与rei发生冲突

### ISSUE THREAD

**Issue by Hanwei233** [Minecraft-LightLand/L2Complements#9]
模组和rei一起装载有概率崩溃游戏
下面是详细日志:
https://pastebin.com/nFuiJrkT

**Comment by lcy0x1** [comment]
我怀疑是REI Plugin Compatibilities的问题，或者是那个优化enum的mod的问题，反正不是REI的问题，也不是L2C的问题，L2C和REI装一起运行过没问题的
